matrix:
  include:
    - os: linux
      language: node_js
      node_js: 7
    - os: osx
      osx_image: xcode10.1
      language: node_js
      node_js: 7
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: 7

before_install:
- printenv

install:
- date

script:
- echo "Yay"

